# Generated by Django 5.0.6 on 2024-06-17 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Element', '0002_element'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ('nom',), 'verbose_name_plural': 'Categories'},
        ),
    ]
